export type Result = [ResponseType, number];

export enum ResponseType {
    REJECT,
    ACCEPT
}

export enum EVENT {
    GAME_INITIALIZE_DOM,
    BANK_DEPOSIT,
    BANK_WITHDRAW,

    EFFECT_GAINED,
    EFFECT_LOST,

    FLAG_DIRTY_GENERATOR,
    FLAG_DIRTY_STATUS_BAR,
    FLAG_DIRTY_UPGRADE,

    GENERATOR_CREATED,
    GENERATOR_RUN,
    GENERATOR_STOP,
    GENERATOR_RECALCULATE,
    GENERATOR_BUY,
    GENERATOR_SELL,

    PLAYER_CLICK,

    TICK_START,
    TICK_END,
    TICK_COUNT,

    POST = "post",
    PRE = "pre"
}